<?php
// Role-based permissions matrix
$rolePermissions = [
    'super_admin' => [
        'dashboard'     => ['view'],
        'students'      => ['view', 'create', 'edit', 'delete'],
        'teachers'      => ['view', 'create', 'edit', 'delete'],
        'courses'       => ['view', 'create', 'edit', 'delete'],
        'attendance'    => ['view', 'create', 'edit', 'delete'],
        'fees'          => ['view', 'create', 'edit', 'delete'],
        'reports'       => ['view'],
        'backup'        => ['view', 'create', 'download', 'delete'],
        'settings'      => ['view', 'edit'],
        'student_cards' => ['view', 'create', 'print'],
        'import'        => ['view', 'import'],
        'users'         => ['view', 'create', 'edit', 'delete'],
        'messaging'     => ['send', 'view'],
    ],
    'admin' => [
        'dashboard'     => ['view'],
        'students'      => ['view', 'create', 'edit', 'delete'],
        'teachers'      => ['view', 'create', 'edit', 'delete'],
        'courses'       => ['view', 'create', 'edit', 'delete'],
        'attendance'    => ['view', 'create', 'edit', 'delete'],
        'fees'          => ['view', 'create', 'edit', 'delete'],
        'reports'       => ['view'],
        'backup'        => ['view', 'create', 'download'],
        'settings'      => ['view', 'edit'],
        'student_cards' => ['view', 'create', 'print'],
        'import'        => ['view', 'import'],
        'users'         => ['view', 'create', 'edit', 'delete'],
        'messaging'     => ['send', 'view'],
    ],
    'accountant' => [
        'dashboard'     => ['view'],
        'students'      => ['view'],
        'teachers'      => ['view'],
        'courses'       => ['view'],
        'attendance'    => ['view'],
        'fees'          => ['view', 'create', 'edit'],
        'reports'       => ['view'],
        'backup'        => [],
        'settings'      => [],
        'student_cards' => [],
        'import'        => [],
        'users'         => [],
        'messaging'     => ['send', 'view'],
    ],
    'teacher' => [
        'dashboard'     => ['view'],
        'students'      => ['view'],
        'teachers'      => [],
        'courses'       => ['view'],
        'attendance'    => ['view', 'create', 'edit'],
        'fees'          => [],
        'reports'       => [],
        'backup'        => [],
        'settings'      => [],
        'student_cards' => [],
        'import'        => [],
        'users'         => [],
    ],
    'reception' => [
        'dashboard'     => ['view'],
        'students'      => ['view', 'create', 'edit'],
        'teachers'      => [],
        'courses'       => ['view'],
        'attendance'    => ['view'],
        'fees'          => ['view'],
        'reports'       => [],
        'backup'        => [],
        'settings'      => [],
        'student_cards' => ['view', 'print'],
        'import'        => [],
        'users'         => [],
        'messaging'     => ['send', 'view'],
    ],
    'viewer' => [
        'dashboard'     => ['view'],
        'students'      => ['view'],
        'teachers'      => ['view'],
        'courses'       => ['view'],
        'attendance'    => ['view'],
        'fees'          => ['view'],
        'reports'       => ['view'],
        'backup'        => [],
        'settings'      => [],
        'student_cards' => [],
        'import'        => [],
        'users'         => [],
    ],
];

$roleLabels = [
    'super_admin' => 'مشرف عام',
    'admin'       => 'مدير',
    'accountant'  => 'محاسب',
    'teacher'     => 'مدرس',
    'reception'   => 'استقبال',
    'viewer'      => 'مشاهد',
];
